export const chatflowTypes = {
    CHANGE_NODE: "CHANGE_NODE",
    CHANGE_EDGE: "CHANGE_EDGE",
    SHOW_POPUP_MENU: "SHOW_POPUP_MENU",
    POPUP_POSITION: "POPUP_POSITION",
    SELECTED_NODE: "SELECTED_NODE",
    SELECTED_PORT: "SELECTED_PORT",
    SHOW_DRAWER: "SHOW_DRAWER",
    DRAWER_DATA: "DRAWER_DATA",
    CHATFLOW_INFO: "CHATFLOW_INFO",
};
export { chatflowTypes as default };