import type { NextPage } from "next";
import Head from "next/head";
import useTranslation from "next-translate/useTranslation";
import { useRouter } from "next/router";
import { useCallback } from "react";
import { loggedIn, loggedOut } from "../stores/actions";
import { useAppDispatch, useAppSelector } from "hooks/reduxHooks";

const Home: NextPage = () => {
  const { isLoggedIn } = useAppSelector((state) => ({
    isLoggedIn: state.auth.isLoggedIn,
  }));
  let { t } = useTranslation("common");
  const router = useRouter();
  const dispatch = useAppDispatch();
  const { locale } = router;

  const changeLocale = useCallback(
    (newLocale) => {
      if (newLocale === "fa-IR") {
        document.querySelector("body").dir = "rtl";
      } else {
        document.querySelector("body").dir = "ltr";
      }
      router.push(router.pathname, router.pathname, { locale: newLocale });
    },
    [router]
  );

  const onClick = async () => {
    console.log(isLoggedIn);

    if (!isLoggedIn) {
      try {
        const data = {
          email: "dfdfddf",
          password: "gdgdggdg",
        };
        await dispatch(loggedIn(data));

        // router.push("/dashboard");
      } catch (e) {}
    } else {
      dispatch(loggedOut());
    }
  };

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        hi
        {/*  <p>{t("login")}</p>
        <p>{isLoggedIn.toString()}</p>
        <ul className="bg-red-600">
          {router?.locales?.map((locale) => (
            <li key={locale}>
              <Link href={router.asPath} locale={locale}>
                <a>{locale}</a>
              </Link>
            </li>
          ))}
        </ul>

        <Link href="/fa-IR" passHref>
          <a className="mr-3" onClick={() => changeLocale("fa-IR")}>
            العربية
          </a>
        </Link>
        <Link href="/en" passHref>
          <a className="mr-3" onClick={() => changeLocale("en")}>
            erffdfxd
          </a>
        </Link>
        <button onClick={onClick}>loginjhj</button>
         */}
      </main>

      <footer></footer>
    </div>
  );
};

export default Home;
